# Generated by Django 5.2.6 on 2026-02-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
